name: Publish

on:
  release:
    types: [ published ]

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020  # v7
        with:
          node-version: '24.20.0' # lts
          registry-url: 'https://registry.npmjs.org'

      - name: Install wasm-pack
        run: |
          curl -L https://github.com/wasm-bindgen/wasm-pack/releases/download/v${{ vars.WASM_PACK_VERSION }}/wasm-pack-v${{ vars.WASM_PACK_VERSION }}-x86_64-unknown-linux-musl.tar.gz | tar xz
          sudo mv wasm-pack-*/wasm-pack /usr/local/bin/

      - name: Install wasm-bindgen-cli
        run: |
          curl -L https://github.com/wasm-bindgen/wasm-bindgen/releases/download/${{ vars.WASM_BINDGEN_VERSION }}/wasm-bindgen-${{ vars.WASM_BINDGEN_VERSION }}-x86_64-unknown-linux-musl.tar.gz | tar xz
          sudo mv wasm-bindgen-*/wasm-bindgen /usr/local/bin/
          sudo mv wasm-bindgen-*/wasm-bindgen-test-runner /usr/local/bin/

      - name: Install wasm-opt
        run: |
          curl -L https://github.com/WebAssembly/binaryen/releases/download/version_${{ vars.WASM_OPT_VERSION }}/binaryen-version_${{ vars.WASM_OPT_VERSION }}-x86_64-linux.tar.gz | tar xz
          sudo mv binaryen-*/bin/wasm-opt /usr/local/bin/

      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown

      - name: Run Native tests
        run: make test

      - name: Authenticate with crates.io
        id: auth
        uses: rust-lang/crates-io-auth-action@c6f97d42243bad5fab37ca0427f495c86d5b1a18 # v1

      - name: Publish core to crates.io
        run: make publish-core
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

      - name: Publish variants to crates.io
        run: make publish-crates
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}

      - name: Run WASM tests
        run: make test-wasm

      - name: Build npm packages
        run: make wasm

      - name: Publish to npm
        run: make publish-npm
